---
name: kite test

on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - master

jobs:
  py_lint:
    name: linting
    runs-on: ubuntu-latest

    steps:
      - name: Prepare environment
        run: |
          python3 -V
          pip3 -V
          python3 -m pip install flake8

      - name: Clone kite repository
        uses: actions/checkout@v2

      - name: Run flake8
        run: python3 -m flake8 *
