---
name: linting

on:
  pull_request:
    branches:
      - "*"

jobs:
  py_lint:
    name: linting
    runs-on: kite-runner

    steps:
      - name: Checkout kite repository
        uses: actions/checkout@v2

      - name: Run flake8
        run: make flake8

      - name: Remove runner
        if: ${{ always() }}
        run: |
          RUNNER_NAME=$(cat /etc/hostname)
          curl -X PUT $KITE_CONTROLLER_API_NETLOC/runner/delete/$RUNNER_NAME > /dev/null 2>&1 &
